export const SAVE_CURRENT_SCORE = "SAVE_CURRENT_SCORE";

export const RESTARTING_CURRENT_SCORE = "RESTARTING_CURRENT_SCORE";

export const SAVE_SCORE_HISTORY = "SAVE_SCORE_HISTORY";

export const TIME_UP = "TIME_UP";

export const SAVE_DICE_CONFIG_BOGGLE = "SAVE_DICE_CONFIG_BOGGLE";
export const EMPTY_DICE_CONFIG_BOGGLE = "EMPTY_DICE_CONFIG_BOGGLE";